### ISSUE TITLE
News + Category > Add Category Filter by Date (Month + Year)

### ISSUE THREAD

**Issue by V-PROUD** [caresvn/vproud.vn#14]
List các tin đã đăng, lọc theo ngày tháng

**Comment by khoipro** [comment]
Dự kiến thời gian làm: 4h.

**Comment by khoipro** [comment]
Chức năng đã được thêm vào @V-PROUD 

> Lưu ý: Chỉ lọc trên các danh mục, còn bản thân trang Tin tức không dùng bộ lọc vì chỉ hiển thị kết quả là bài viết mới nhất.

Vị trí lựa chọn lọc:

![Screenshot at Sep 06 00-39-15](https://user-images.githubusercontent.com/10395311/64365655-d31db500-d03e-11e9-9180-965cb3af3f72.png)

Khi được lọc:

![Screenshot at Sep 06 00-39-33](https://user-images.githubusercontent.com/10395311/64365691-e16bd100-d03e-11e9-9f52-c301eed9fdf1.png)
